package com.cybershield.repository;

import com.cybershield.model.Alert;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

/**
 * AlertRepository provides data-access operations for {@link Alert} entities
 * generated by the Intrusion Detection System (IDS) module of CyberShield CSMS.
 *
 * <p>Extends {@link JpaRepository} to inherit standard CRUD operations and adds
 * custom query methods whose SQL is auto-generated by Spring Data JPA from the
 * method names (derived-query strategy).</p>
 *
 * @author CyberShield Team
 * @version 1.0
 */
@Repository
public interface AlertRepository extends JpaRepository<Alert, Long> {

    /**
     * Returns all alerts that have not yet been marked as resolved by an analyst.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM alerts WHERE is_resolved = false}</p>
     *
     * <p>Used by the IDS dashboard panel and the active-threat count API to surface
     * alerts that still require human review.</p>
     *
     * @return a {@link List} of unresolved {@link Alert} entities; empty list if all are resolved
     */
    List<Alert> findByIsResolvedFalse();

    /**
     * Returns all alerts matching the specified severity classification.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM alerts WHERE severity = :severity}</p>
     *
     * <p>Typical severity values are {@code "CRITICAL"}, {@code "HIGH"},
     * {@code "MEDIUM"}, and {@code "LOW"}.</p>
     *
     * @param severity the severity string to filter by
     * @return a {@link List} of {@link Alert} entities with the given severity;
     *         empty list if none found
     */
    List<Alert> findBySeverity(String severity);

    /**
     * Counts the total number of unresolved alerts currently in the system.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT COUNT(*) FROM alerts WHERE is_resolved = false}</p>
     *
     * <p>Used by the dashboard statistics endpoint to report active threat count
     * without loading full entity objects into memory.</p>
     *
     * @return the number of alerts where {@code isResolved} is {@code false}
     */
    long countByIsResolvedFalse();

    /**
     * Returns all alerts detected after the specified timestamp.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM alerts WHERE detected_at > :after}</p>
     *
     * <p>Useful for filtering alerts to a specific time window, such as "all alerts
     * detected today" when {@code after} is set to the start of the current day.</p>
     *
     * @param after the lower bound timestamp (exclusive); alerts detected exactly at
     *              this time are <em>not</em> included
     * @return a {@link List} of {@link Alert} entities detected after the given time;
     *         empty list if none found
     */
    List<Alert> findByDetectedAtAfter(LocalDateTime after);
}
