package com.cybershield.repository;

import com.cybershield.model.FirewallRule;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * FirewallRuleRepository provides data-access operations for {@link FirewallRule} entities.
 *
 * <p>Extends {@link JpaRepository} to inherit standard CRUD operations and adds
 * custom query methods whose SQL is auto-generated by Spring Data JPA from the
 * method names (derived-query strategy).</p>
 *
 * @author CyberShield Team
 * @version 1.0
 */
@Repository
public interface FirewallRuleRepository extends JpaRepository<FirewallRule, Long> {

    /**
     * Returns all currently active firewall rules ordered by their priority value
     * in ascending order (lowest priority number = highest precedence).
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM firewall_rules WHERE is_active = true ORDER BY priority ASC}</p>
     *
     * <p>Used by the {@code FirewallEngine} to evaluate incoming traffic against
     * the ordered active ruleset.</p>
     *
     * @return a priority-ordered {@link List} of active {@link FirewallRule} entities;
     *         empty list if no active rules exist
     */
    List<FirewallRule> findByIsActiveTrueOrderByPriorityAsc();

    /**
     * Returns all firewall rules with the specified action string.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM firewall_rules WHERE action = :action}</p>
     *
     * <p>Typical action values are {@code "ALLOW"} and {@code "BLOCK"}.</p>
     *
     * @param action the action string to filter by (e.g., {@code "ALLOW"}, {@code "BLOCK"})
     * @return a {@link List} of {@link FirewallRule} entities matching the action;
     *         empty list if none found
     */
    List<FirewallRule> findByAction(String action);

    /**
     * Counts the total number of currently active firewall rules.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT COUNT(*) FROM firewall_rules WHERE is_active = true}</p>
     *
     * <p>Used by the dashboard statistics endpoint to report the active rule count
     * without loading full entity objects.</p>
     *
     * @return the count of active {@link FirewallRule} records
     */
    long countByIsActiveTrue();
}
