package com.cybershield.repository;

import com.cybershield.model.LogEntry;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;

/**
 * LogRepository provides data-access operations for {@link LogEntry} entities.
 *
 * <p>Extends {@link JpaRepository} to inherit standard CRUD operations and adds
 * custom query methods whose SQL is auto-generated by Spring Data JPA from the
 * method names (derived-query strategy). All list-returning methods use
 * {@link Pageable} to support server-side pagination.</p>
 *
 * @author CyberShield Team
 * @version 1.0
 */
@Repository
public interface LogRepository extends JpaRepository<LogEntry, Long> {

    /**
     * Returns a paginated list of log entries matching the given event type.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM log_entries WHERE event_type = :eventType LIMIT/OFFSET per Pageable}</p>
     *
     * @param eventType the event category string to filter by (e.g., "LOGIN", "FIREWALL_BLOCK")
     * @param pageable  pagination and sorting parameters
     * @return a {@link Page} of matching {@link LogEntry} objects
     */
    Page<LogEntry> findByEventType(String eventType, Pageable pageable);

    /**
     * Returns a paginated list of log entries matching the given severity level.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM log_entries WHERE severity = :severity LIMIT/OFFSET per Pageable}</p>
     *
     * @param severity the severity string to filter by (e.g., "HIGH", "MEDIUM", "LOW")
     * @param pageable pagination and sorting parameters
     * @return a {@link Page} of matching {@link LogEntry} objects
     */
    Page<LogEntry> findBySeverity(String severity, Pageable pageable);

    /**
     * Returns a paginated list of log entries originating from the given source IP address.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM log_entries WHERE source_ip = :sourceIP LIMIT/OFFSET per Pageable}</p>
     *
     * @param sourceIP the IP address string to filter by
     * @param pageable pagination and sorting parameters
     * @return a {@link Page} of matching {@link LogEntry} objects
     */
    Page<LogEntry> findBySourceIP(String sourceIP, Pageable pageable);

    /**
     * Returns a paginated list of log entries whose timestamp falls within the given range.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM log_entries WHERE timestamp BETWEEN :start AND :end LIMIT/OFFSET per Pageable}</p>
     *
     * <p>Both bounds are inclusive. Useful for audit reports scoped to a specific time window.</p>
     *
     * @param start    the start of the date-time range (inclusive)
     * @param end      the end of the date-time range (inclusive)
     * @param pageable pagination and sorting parameters
     * @return a {@link Page} of {@link LogEntry} objects within the specified range
     */
    Page<LogEntry> findByTimestampBetween(LocalDateTime start, LocalDateTime end, Pageable pageable);

    /**
     * Counts log entries of a specific event type recorded after the given timestamp.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT COUNT(*) FROM log_entries WHERE event_type = :type AND timestamp > :after}</p>
     *
     * <p>Used by the dashboard to compute counts like "FIREWALL_BLOCK events today".</p>
     *
     * @param type  the event type string to match (e.g., "FIREWALL_BLOCK")
     * @param after the lower bound timestamp (exclusive)
     * @return the number of matching log entries
     */
    long countByEventTypeAndTimestampAfter(String type, LocalDateTime after);

    /**
     * Counts all log entries recorded after the given timestamp.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT COUNT(*) FROM log_entries WHERE timestamp > :after}</p>
     *
     * <p>Used by the dashboard to compute the total "events today" metric.</p>
     *
     * @param after the lower bound timestamp (exclusive); typically midnight of the current day
     * @return the total number of log entries recorded after the given time
     */
    long countByTimestampAfter(LocalDateTime after);
}
