package com.cybershield.repository;

import com.cybershield.model.Role;
import com.cybershield.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * UserRepository provides data-access operations for {@link User} entities.
 *
 * <p>Extends {@link JpaRepository} to inherit standard CRUD operations and adds
 * custom query methods whose SQL is auto-generated by Spring Data JPA from the
 * method names (derived-query strategy).</p>
 *
 * @author CyberShield Team
 * @version 1.0
 */
@Repository
public interface UserRepository extends JpaRepository<User, Long> {

    /**
     * Looks up a single user by their unique login username.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM users WHERE username = :username LIMIT 1}</p>
     *
     * @param username the exact username to search for (case-sensitive)
     * @return an {@link Optional} containing the matched {@link User}, or empty if not found
     */
    Optional<User> findByUsername(String username);

    /**
     * Looks up a single user by their registered email address.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM users WHERE email = :email LIMIT 1}</p>
     *
     * @param email the exact email address to search for (case-sensitive)
     * @return an {@link Optional} containing the matched {@link User}, or empty if not found
     */
    Optional<User> findByEmail(String email);

    /**
     * Returns all users assigned to a specific application role.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM users WHERE role = :role}</p>
     *
     * @param role the {@link Role} enum value to filter by (e.g., ADMIN, ANALYST, VIEWER)
     * @return a {@link List} of users with the specified role; empty list if none found
     */
    List<User> findByRole(Role role);

    /**
     * Checks whether any user record with the given username already exists.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT COUNT(*) > 0 FROM users WHERE username = :username}</p>
     *
     * <p>Preferred over {@link #findByUsername(String)} when only existence matters,
     * as it avoids loading the full entity.</p>
     *
     * @param username the username to check for existence
     * @return {@code true} if at least one user with this username exists, {@code false} otherwise
     */
    boolean existsByUsername(String username);

    /**
     * Returns all users whose accounts are currently active.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM users WHERE is_active = true}</p>
     *
     * @return a {@link List} of active {@link User} entities; empty list if none found
     */
    List<User> findByIsActiveTrue();

    /**
     * Returns all users whose lockout period has not yet expired at the given timestamp.
     *
     * <p>Generated SQL equivalent:
     * {@code SELECT * FROM users WHERE locked_until > :now}</p>
     *
     * <p>Used by the authentication service to identify currently locked accounts.</p>
     *
     * @param now the reference timestamp (typically {@link LocalDateTime#now()})
     * @return a {@link List} of {@link User} entities that are still locked; empty list if none
     */
    List<User> findByLockedUntilAfter(LocalDateTime now);
}
